# Description:
#   West Vlaamse spreuken
#
# Dependencies:
#   None
#
# Configuration:
#   None
#
# Commands:
#   hubot wuk
#
# Author:
#   @joggink

quotes = [
		"'k go'n ier rap min puste schèren",
		"'t is ol gin oar snien",
		"'t is gin kloatn weird",
		"wat geef ik aan een man",
		"de hetten an en",
		"Bachtn de kupe",
		"schutels",
		"alles goed , oallemolle goed ( iepers )",
		"wisterkapjile",
		"A de katte van us es dansn de muzn",
		"'t is all niet dat oar snien, 't is all die kruljes legn",
		"(h)eur oir'neen getuut",
		"jahoenoeine",
		"mit de poepers zitten",
		"in z'n broek doen",
		"Kloshjaar",
		"bie ze pietje pakken",
		"Bie d'n buk gezet weirdn",
		"smot upbeutrn",
		"stutte smeiren",
		"stuutn brièn",
		"stuutn brièn",
		"kopen (een kind kopen)",
		"'Korten da na!",
		"ja beter in zin broek gesketen",
		"ie is te ljilijk om te elpn dundrn.",
		"Dat is de pad op zeven",
		"de batterie is luzzeplat",
		"'t zwyn deur de bjèt'n joag'n",
		"'t zwin in de bjitn joagen",
		"'t zwien de bjetn injoagen",
		"d' euzjes leeken",
		"den diek",
		"den uul van 't spel zien",
		"d'eiers gan roven",
		"ons poezeke is schijl",
		"de Russen zijn in Paris",
		"tante Marie is up bezoek",
		"de roo vlagge angt uut",
		"de kiekens zitten deurn droad",
		"'t is punaisekermesse",
		"de kraaien goant uutbringn",
		"a ten appel te verre van den bome valt",
		"t belangrikste sta tusn aksjtjes",
		"doet ne kier zelve",
		"dwoaze kalle",
		"Verkelkereerd",
		"de meulnare versmoren",
		"zin oorring'n an ein",
		"zoa dronke lik zeevn polischiès",
		"jis anaozel dubble toe",
		"é djok geven",
		"t'is een bjele",
		"een vet vrouwmens",
		"fring in de busse",
		"zis nie goet e streken (iepers )",
		"eenn leven lik een Duutschen oorloge",
		"nen tuk doen",
		"In kennisse zin",
		"z'is koopziende",
		"slaap'n mi 't lank kordeeël",
		"oe oeder de kapelle, oe mjir da je ze moe versieren",
		"tjoalpre",
		"In kenisse zien",
		"'t kolsietje van templeuf",
		"nen dah conferènche",
		"'t zwin deur de bjêten joagn",
		"De weirld is ne grwote zwienebak, en die meest sloebert ee meest! Verwant met: de stoetste wezels zuupen de grootste eiers.",
		"ek ze goeste",
		"'t es tit tat 't ut es",
		"T'is nee rute ut 't us en at rint rint terin",
		"tis e rut ut tus en ot rint trint drin",
		"'t Is e rututus en a trintrintrin",
		"tis e rut ut ut us, en at rint, trint trin",
		"God macht weten",
		"je stinkt lik un oe'kt oere",
		"je dient nie voe zwijnejoengen te pakken",
		"preus lik ne zak slunsen",
		"NE VELO ME NE TORPRDO",
		"ne keemel skietn",
		"bie de buk doen",
		"goje zaagn",
		"fret va je gat tis gin vriedag",
		"Het zwien deur de vinster angn'",
		"gekruund moa nie geruund",
		"buzze ein",
		"je zoet een frang in tweien bieten",
		"'d zeegn tje (e bewoare je)",
		"GOED DAG",
		"eetn lik nen dikkedelver",
		"goed'n zjuubleie vieër(z)'n",
		"vele volk in de stoasje",
		"werken knie over elleboge",
		"Ej i je kloat'n gekapt",
		"Ej je petat'n uphoogt",
		"Et da lam oai? Joat da lam et oai. Da lam et oai at da lam oai et",
		"Spuugen lik nen reiger",
		"'t hoar zoudt deur joen klakke groeien",
		"kerjoole vieër'n",
		"'t ligt met zien pooten omooge",
		"joe jeun', joe henèr'n",
		"'t gaapt geliek é oven",
		"t'goat moljoegn rinn",
		"'t Zit effen dikke, 't Goa kattejongen spuien",
		"'t mesan't nië",
		"tis an gieder",
		"'t is a(n) jundre",
		"'T sop es de koole nie weird",
		"tès 'n platpisserke",
		"t oedt niet in",
		"tes van lekt min luptje",
		"moh tis e batje",
		"Tès ol gin oar snien, (tès ol die splette leggen)",
		"t'shoap is de preute of",
		"tetidtatute (vettige e)",
		"Zin lief es achter brood",
		"ti lik ofdaketik zegn",
		"'t Steekt nie op een jûûnpelle",
		"tis gennavanse",
		"'t oenderste uut de kanne willen",
		"t smoort",
		"té nie meugn zin",
		"er geen "sjense" meer voor hebben",
		"de rutte der ut en trint der in",
		"'t rint, 't giet",
		"het rint dat 't zikt",
		"'t regnt mullejoengn",
		"de rin voalt lik schitte ut de lucht",
		"'t kom nie ip e tette van ne mierebuk",
		"tjoene",
		"Twa bre smitn!",
		"J'eet geene noagle voer an zien gat te skarten",
		"Ziene keldre valt in",
		"Te jin vant college wi",
		"ne noch kind noch kraaie",
		"Jee nog nooit strwo van d'erde gerapt",
		"énet olsan de rippe of de schitte",
		"J'is oei patat",
		"j'eet u scheute gekreg'n",
		"e ruttelt inze vel",
		"ti gin te rapn",
		"Je brjed wok zin stutjes zelve",
		"'t is van de gierigaard deure en de krempkloot were",
		"Jès were den ul van 't spel",
		"Jis op z'n sterre gestekt zeker",
		"jeet een tonge van lientjes",
		"'t es'tn gescheten en gespogen",
		"hij miek ur veel spel over",
		"je miek ur veel spel over",
		"ie goa scheetn loatn wi",
		"hij wil niet lammeren",
		"J' es moa g'acht lik 't oor an zin skoen",
		"oe eki je mule",
		"oedt j' an 't gas",
		"ge moetj mulle hoedn",
		"oud ju mulle !",
		"oekt jun brefellen",
		"in zyn roap'n schyt'n",
		"é teustje drienken",
		"kpeist abbij",
		"Kzint zo moe lik koude keirre pap",
		"kzyn effn streke",
		"ik zin nie zindelijk",
		"kzint gat in",
		"kzint bus(bos) in",
		"kzin noa mn nest, kgoan noa mn kaf",
		"ken der woeste in, 'k èn doar goeste vwoaren",
		"Ken e sjikellette i me bekke",
		"'k en der hoeste in",
		"keni nog nois e wetn",
		"kzieje gèrn",
		"in plan loat'n",
		"in de piense oeden",
		"vernesteld zien",
		"in een schoffelschote",
		"In de weirdie van gjeen tied",
		"in ruzie voln",
		"joa wadde",
		"Je zie va lotje getikt",
		"je go nog mien stoake uuttrekke'n.",
		"ge zoet er de koede kwak van krieg'n,tis vo mieretetjes va te kriegn, Je kriegt d'r ennebubbels van",
		"os koken kiken me ze linke gibus",
		"der zit un uul ip je dak",
		"der zit un ul ip je dak",
		"gie moet je mulle odn",
		"je lat der gin gras over groein",
		"je wit waje moe doejn ?",
		"je got anden ols briegn",
		"katje spelen",
		"Ik heb het ermee gehad.",
		"de kletskop loaten spugen",
		"'n skeute lossn",
		"Kom ier !! Kgoj in slùsn trekng",
		"doar joen boantjes kun' ip te wjèke leg'n",
		"'t zwien in de bjiten jagen",
		"gif moar goaze",
		"buzze",
		"skit in'n dyk",
		"go goan zanten !",
		"Scheurt je puste",
		"van bachn de kuppe",
		"un gat is'n gat, en nen piet è gjèn og'n",
		"Mien koesen slokeren",
		"mien retje",
		"A schon keuntje",
		"jittn beir",
		"schoane lietjes deur'n nie lange",
		"witte perrieges èn veele strooëi nooëdieg",
		"smukn",
		"Schieter avagen",
		"gin roste klute weird zien",
		"kerieuzeneuzen en vrah'n stell'n",
		"een toer meedraaien",
		"Nouw brek mien de klump.",
		"ip elk potje past er 'n ulleke",
		"tis em gespoog'n",
		"er je boantjes ip te wjèke leg'n",
		"Up u doze vollen, ip ui mulle dèssen",
		"op ze piekbeste",
		"een hogen top scheren",
		"tes wok moa de rwoak van de kozve da doa verloorn hoat",
		"schart je an un ezel zun mule je kriegt u bete, schart je an ze gat je kriegt u schete",
		"z'n patatten afgieten",
		"upkomn gelik de schitte",
		"den trap doen",
		"radio open draaien",
		"in stokke komn , in boel komn , spel en",
		"juttekoker",
		"zwarte schole oen (zwarte school houden)",
		"de zwiens loop'n me stroaj in under muule.",
		"doe jen rutte toe",
		"tis topn dat smakt in die vulle mulle van gie",
		"een blauwmeske (mis) doen",
		"ze sjieke uutspugen",
		"Leg mo et stille",
		"een schete in een netzak",
		"tis tied dathuut is",
		"tot de noaste keer",
		"Nie van nen oaze gepoept zien (niet door een haas verwekt zijn)",
		"ut n'oak zin",
		"ip tsjok goan",
		"z'n zaligheid zeggen",
		"ge zi wok t skerpste mes nie uit t skof é gie",
		"tis e beskeetn kommisje",
		"va e skeete nen donderslag moaken",
		"de kluts kwiet zien",
		"A' j'an een peene trekt, heel den 'ut ruttelt.",
		"ze karre keren",
		"bezikte zak",
		"'t katje bie de melk zetten",
		"sien nogen draaien naar tolvansiengat",
		"der zyn nohol wel poat'n en oar'n an",
		"vremd goan, ip een andre goan, scheve schatse rien, verandren van toespieze",
		"tieluk ip joen stik'n zyn",
		"Woa bluuft da wuufe ?",
		"wienne ziej antkraam-foefln",
		"Wa peij doar of?",
		"Zukke snelle kokketeute",
		"wuk ej gezeit",
		"mogowze",
		"wadist",
		"de meur!!!",
		"skit in de bjitn é vint",
		"kgo mine puestje skarten",
		"we hoa hoa hoa hoan",
		"me zijn weg",
		"Zijn schupe afkuus'n",
		"z'n puuste scheurn",
		"west-vloandern",
		"God wit wiens 'oofd doet er toen zjeer",
		"moej een stiksjen en",
		"Goa je nui feitelijk agauwe uien bek ouwen??",
		"zoektj'spel?,wildj boeL?,moeje een vuste vangn??",
		"Goat goan joa?",
		"men ouders slapen beneden he",
		"zal jou missen",
		"euren ekster weunt hoge",
		"je ku ze deur e gote trekken",
		"ze dot den trap, tis lik een otostrade",
		"koppekeijard",
		"Smoet je kiet'n moar in",
		"Zwanst eki nie",
		"In zien gat gebet'n zien",
		"zullie kunne nie mee mekaore overweg",
		"zin oanzichte spreekt boekdjiln",
		"zit een schof",
		"oed joe troape",
		" oed joe muulle",
		"odjemulle!"
]

module.exports = (robot) ->

  robot.hear /wuk/i, (msg) ->
    msg.send msg.random quotes